# Generated by Django 3.2.3 on 2021-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='display_type',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='type',
            new_name='name',
        ),
    ]
