# Generated by Django 3.2.3 on 2021-06-03 21:19

from django.db import migrations, models
import django.db.models.deletion
import product_banner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_path', models.ImageField(upload_to=product_banner.models.ProductBanner.get_upload_path)),
                ('is_active', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
