# Generated by Django 3.2.3 on 2021-06-23 02:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('productManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
