# Generated by Django 3.2.3 on 2021-06-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product_combination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombination',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_combinations', to='product.product'),
        ),
    ]
