# Generated by Django 3.2.3 on 2021-06-03 21:19

from django.db import migrations, models
import django.db.models.deletion
import product_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product_image.models.ProductImage.get_upload_path)),
                ('product_image_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_image_gallery.productimagegallery')),
            ],
        ),
    ]
