# Generated by Django 3.2.3 on 2021-06-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_image_gallery', '0002_productimagegallery_product'),
        ('product_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image', to='product_image_gallery.productimagegallery'),
        ),
    ]
