# Generated by Django 3.2.3 on 2021-06-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant_value', '0001_initial'),
        ('product', '0001_initial'),
        ('variant', '0001_initial'),
        ('product_variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='variant.variant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='variant_value.variantvalue'),
        ),
    ]
