# Generated by Django 3.2.3 on 2021-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255, unique_for_date='created_at'),
        ),
    ]
