# Generated by Django 3.2.3 on 2021-06-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.variant')),
            ],
        ),
    ]
