# Generated by Django 3.2.3 on 2021-06-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
        ('variant_value', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantvalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='variant.variant'),
        ),
    ]
