# Generated by Django 3.2.3 on 2021-06-03 21:19

from django.db import migrations, models
import django.db.models.deletion
import product_image_gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_variant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=product_image_gallery.models.ProductImageGallery.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_variant.productvariant')),
            ],
        ),
    ]
