# Generated by Django 3.2.3 on 2021-06-04 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('product_variant', '0001_initial'),
        ('product_image_gallery', '0002_productimagegallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagegallery',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_gallery', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productimagegallery',
            name='product_variant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_gallery', to='product_variant.productvariant'),
        ),
    ]
