# Generated by Django 3.2.3 on 2021-06-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant_value', '0002_alter_variantvalue_variant'),
        ('product_image_gallery', '0003_auto_20210604_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimagegallery',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='productimagegallery',
            name='variant_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_gallery', to='variant_value.variantvalue'),
        ),
    ]
